countries_en = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia",
    "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
    "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
    "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia",
    "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
    "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador",
    "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji",
    "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
    "Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq",
    "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait",
    "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
    "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius",
    "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (formerly Burma)",
    "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia",
    "Norway", "Oman", "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
    "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines",
    "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
    "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan",
    "Suriname", "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga",
    "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates",
    "United Kingdom", "United States of America", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen",
    "Zambia", "Zimbabwe"]

countries_uk = [
    "Афганістан", "Албанія", "Алжир", "Андорра", "Ангола", "Антигуа і Барбуда", "Аргентина", "Вірменія", "Австралія",
    "Австрія", "Азербайджан", "Багами", "Бахрейн", "Бангладеш", "Барбадос", "Білорусь", "Бельгія", "Беліз", "Бенін",
    "Бутан", "Болівія", "Боснія і Герцеговина", "Ботсвана", "Бразилія", "Бруней", "Болгарія", "Буркіна-Фасо", "Бурунді",
    "Кабо-Верде", "Камбоджа", "Камерун", "Канада", "Центральноафриканська Республіка", "Чад", "Чилі", "Китай", "Колумбія",
    "Комори", "Конго (Конго-Браззавіль)", "Коста-Ріка", "Хорватія", "Куба", "Кіпр", "Чехія (Чеська Республіка)",
    "Демократична Республіка Конго (Конго-Кіншаса)", "Данія", "Джибуті", "Домініка", "Домініканська Республіка", "Еквадор",
    "Єгипет", "Сальвадор", "Екваторіальна Гвінея", "Ерітрея", "Естонія", "Есватіні (колишня Свазіленд)", "Ефіопія", "Фіджі",
    "Фінляндія", "Франція", "Габон", "Гамбія", "Грузія", "Німеччина", "Гана", "Греція", "Гренада", "Гватемала", "Гвінея",
    "Гвінея-Бісау", "Гайана", "Гаїті", "Святий Престол", "Гондурас", "Угорщина", "Ісландія", "Індія", "Індонезія", "Іран", "Ірак",
    "Ірландія", "Ізраїль", "Італія", "Кот-д'Івуар", "Ямайка", "Японія", "Йорданія", "Казахстан", "Кенія", "Кірібаті", "Кувейт",
    "Киргизстан", "Лаос", "Латвія", "Ліван", "Лесото", "Ліберія", "Лівія", "Ліхтенштейн", "Литва", "Люксембург", "Мадагаскар",
    "Малаві", "Малайзія", "Мальдіви", "Малі", "Мальта", "Маршаллові острови", "Мавританія", "Маврикій", "Мексика", "Мікронезія",
    "Молдова", "Монако", "Монголія", "Чорногорія", "Марокко", "Мозамбік", "М'янма (колишня Бірма)", "Намібія", "Науру", "Непал",
    "Нідерланди", "Нова Зеландія", "Нікарагуа", "Нігер", "Нігерія", "Північна Корея", "Північна Македонія", "Норвегія", "Оман",
    "Пакистан", "Палау", "Держава Палестина", "Панама", "Папуа-Нова Гвінея", "Парагвай", "Перу", "Філіппіни", "Польща", "Португалія",
    "Катар", "Румунія", "Росія", "Руанда", "Сент-Кіттс і Невіс", "Сент-Люсія", "Сент-Вінсент і Гренадини", "Самоа", "Сан-Марино",
    "Сан-Томе і Принсіпі", "Саудівська Аравія", "Сенегал", "Сербія", "Сейшельські острови", "Сьєрра-Леоне", "Сінгапур", "Словаччина",
    "Словенія", "Соломонові острови", "Сомалі", "Південна Африка", "Південна Корея", "Південний Судан", "Іспанія", "Шрі-Ланка",
    "Судан", "Суринам", "Швеція", "Швейцарія", "Сирія", "Таджикистан", "Танзанія", "Таїланд", "Тімор-Лешті", "Того", "Тонга",
    "Тринідад і Тобаго", "Туніс", "Туреччина", "Туркменістан", "Тувалу", "Уганда", "Україна", "Об'єднані Арабські Емірати",
    "Сполучене Королівство Великої Британії і Північної Ірландії", "Сполучені Штати Америки", "Уругвай", "Узбекистан", "Вануату",
    "Венесуела", "В'єтнам", "Ємен", "Замбія", "Зімбабве"
]

